### ISSUE TITLE
No provider for ViewportRuler

### ISSUE THREAD

**Issue by aglotero** [mainflux/mainflux-ui#1]
Hi!
From a fresh git clone I run

`npm intall`

and after:

`ng serve`

when I try to reach the application these errors are logged at console:

Unhandled Promise rejection: Error in ./MdButton class MdButton - inline template:0:64 caused by: No provider for ViewportRuler! ; Zone: angular ; Task: Promise.then ; Value: Object { _nativeError: Error, originalError: Object, context: Object, stack: "" } BaseError@http://127.0.0.1:4200/main.bundle.js:4443:27
AbstractProviderError@http://127.0.0.1:4200/main.bundle.js:46553:9
NoProviderError@http://127.0.0.1:4200/main.bundle.js:46584:9
ReflectiveInjector_</ReflectiveInjector_.prototype._throwOrNull@http://127.0.0.1:4200/main.bundle.js:68758:19
ReflectiveInjector_</ReflectiveInjector_.prototype._getByKeyDefault@http://127.0.0.1:4200/main.bundle.js:68786:20
ReflectiveInjector_</ReflectiveInjector_.prototype._getByKey@http://127.0.0.1:4200/main.bundle.js:68749:20
ReflectiveInjector_</ReflectiveInjector_.prototype.get@http://127.0.0.1:4200/main.bundle.js:68558:16
NgModuleInjector</NgModuleInjector.prototype.get@http://127.0.0.1:4200/main.bundle.js:47255:40
AppView</AppView.prototype.injectorGet@http://127.0.0.1:4200/main.bundle.js:69300:26
DebugAppView</DebugAppView.prototype.injectorGet@http://127.0.0.1:4200/main.bundle.js:69542:20
ElementInjector</ElementInjector.prototype.get@http://127.0.0.1:4200/main.bun[…]

I'm new using AngularJS applications, so I appreciate any advice in how to debug this issue.

Regards,
André

**Comment by drasko** [comment]
@aglotero I did not try yet `mainflux-ui`, @nmarcetic is working on this - probably he will have more info. But I know that this is not ready yet - it is WIP.

UI is not a priority for now, we are still building backend services and currently we are focused on security. But I expect that some first version might be finished in a couple of weeks...

Mainflux is quite usable even without administrative UI - you can provision devices and manage them via REST API.

**Comment by nmarcetic** [comment]
@aglotero Thank your for reporting this. It was fixed with https://github.com/mainflux/mainflux-ui/commit/88e62b7c3c83a2f6963290d58271775f8853d15a  You can now pull the changes.
As @drasko told you its still WIP, not ready yet, but its top priority in our TODO list, so stay tuned ;)

**Comment by drasko** [comment]
@nmarcetic great. I agree that we need some kind of basic UI ASAP that can be used for demo purposes and easy onboarding of people who want to give Mainflux a try.

**Comment by nmarcetic** [comment]
Closing this one with https://github.com/mainflux/mainflux-ui/commit/88e62b7c3c83a2f6963290d58271775f8853d15a
